### ISSUE TITLE
Include other changes than methods into history list

### ISSUE THREAD

**Issue by SilvanVerhoeven** [hpi-swa-teaching/ChangesBrowser#81] opened 2020-06-14 10:01 UTC
As a developer, I also want to work with doIts that have persistent effects on my image within the history list because I want to administrate all code changing changes.

**Acceptance criteria:**
* [ ] History list shows all doIts, the respective change of that doIt is shown in the change list
* [ ] History list shows all changed methods, the changes affecting one method are shown in the change list

**Comment by marcelgarus** [comment] 2020-06-14 11:31
Duplicate of #54

**Closed** 2020-06-14 11:31 UTC
Labels: Story Points: 8, User Story
